/**
 * Bihar cascading location data: District -> Block -> Panchayat[]
 */
export const BIHAR_LOCATION_DATA: Record<string, Record<string, string[]>> = {
  "Araria": {
    "Araria": ["Araria R.S.", "Aamgachhi", "Simarbha"],
    "Bhargama": ["Bhargama", "Bishariya", "Jhitki"],
    "Forbesganj": ["Forbesganj", "Simraha", "Bathanaha"],
    "Jokihat": ["Jokihat", "Matapur", "Baghahar"],
    "Kursakanta": ["Kursakanta", "Kshatiyana", "Jhikariya"],
    "Narpatganj": ["Narpatganj", "Basantpur", "Kushmha"],
    "Palasi": ["Palasi", "Chakla", "Dagarua"],
    "Raniganj": ["Raniganj", "Belsandi", "Bargama"]
  },
  "Arwal": {
    "Arwal": ["Arwal", "Kaler", "Bansi"],
    "Kaler": ["Kaler", "Akhtiyarpur", "Karpi"],
    "Karpi": ["Karpi", "Belkhara", "Shorampur"],
    "Kura": ["Kura", "Sonadand", "Mahmudpur"],
    "Sonepur": ["Sonepur", "Bishunpur", "Chandpur"]
  },
  "Aurangabad": {
    "Aurangabad": ["Aurangabad", "Dev", "Karma"],
    "Barun": ["Barun", "Jaso", "Bansa"],
    "Daudnagar": ["Daudnagar", "Obra", "Keshpa"],
    "Goh": ["Goh", "Dihri", "Bara"],
    "Haspura": ["Haspura", "Itwan", "Kopa"],
    "Kutumba": ["Kutumba", "Amba", "Ledwa"],
    "Madanpur": ["Madanpur", "Salaiya", "Tarari"],
    "Nabinagar": ["Nabinagar", "Ankhori", "Tandwa"],
    "Obra": ["Obra", "Daipur", "Gopalpur"],
    "Rafiganj": ["Rafiganj", "Moth", "Kothi"]
  },
  "Banka": {
    "Amarpur": ["Amarpur", "Pachrukhi", "Sankarpur"],
    "Banka": ["Banka", "Bhalua", "Bathani"],
    "Barhat": ["Barhat", "Chandan", "Punsia"],
    "Bounsi": ["Bounsi", "Katoria", "Kusum"],
    "Chandan": ["Chandan", "Dhuraiya", "Gangania"],
    "Dhuraiya": ["Dhuraiya", "Katoria", "Rajoun"],
    "Katoria": ["Katoria", "Banka", "Chandan"],
    "Phulidumar": ["Phulidumar", "Suriya", "Belhar"],
    "Rajoun": ["Rajoun", "Banka", "Amarpur"],
    "Shambhuganj": ["Shambhuganj", "Kharika", "Punsia"]
  },
  "Begusarai": {
    "Bachhwara": ["Bachhwara", "Chamtha", "Rauta"],
    "Bakhri": ["Bakhri", "Salempur", "Chhouharni"],
    "Ballia": ["Ballia", "Lakho", "Pokhariya"],
    "Barauni": ["Barauni", "Teghra", "Phulwaria"],
    "Begusarai": ["Begusarai", "Matihani", "Kapan"],
    "Bhagwanpur": ["Bhagwanpur", "Mehdipur", "Bishnupur"],
    "Birpur": ["Birpur", "Malhipur", "Garhara"],
    "Cheria Bariarpur": ["Cheria Bariarpur", "Supaul", "Mahendrapur"],
    "Chhorahi": ["Chhorahi", "Garhpura", "Khudawandpur"],
    "Garhpura": ["Garhpura", "Ratanpur", "Sakit"],
    "Khodawandpur": ["Khodawandpur", "Mehsour", "Cheria"],
    "Mansurchak": ["Mansurchak", "Ajgaiba", "Sabdalpur"],
    "Matihani": ["Matihani", "Rampur", "Shankarpur"],
    "Sahebpur Kamal": ["Sahebpur Kamal", "Rashidpur", "Sanha"],
    "Teghra": ["Teghra", "Baro", "Madhurapur"]
  },
  "Bhagalpur": {
    "Bihpur": ["Bihpur", "Narayanpur", "Kharik"],
    "Gopalpur": ["Gopalpur", "Ismailpur", "Rangra"],
    "Kahalgaon": ["Kahalgaon", "Srirampur", "Ghogha"],
    "Kharik": ["Kharik", "Bihpur", "Narayanpur"],
    "Naugachhia": ["Naugachhia", "Madhepur", "Teghra"],
    "Narayanpur": ["Narayanpur", "Bihpur", "Kharik"],
    "Pirpainti": ["Pirpainti", "Barari", "Shibnarayanpur"],
    "Rangra Chowk": ["Rangra", "Gopalpur", "Ismailpur"],
    "Sabour": ["Sabour", "Mirzachowki", "Lailakh"],
    "Shahkund": ["Shahkund", "Kharik", "Panjwara"],
    "Sultanganj": ["Sultanganj", "Maheshpur", "Asarganj"]
  },
  "Bhojpur": {
    "Agiaon": ["Agiaon", "Piro", "Sahar"],
    "Arrah": ["Arrah", "Koilwar", "Barhara"],
    "Barhara": ["Barhara", "Sinha", "Gunari"],
    "Bihiya": ["Bihiya", "Jagdishpur", "Garhani"],
    "Garhani": ["Garhani", "Piro", "Sandesh"],
    "Jagdishpur": ["Jagdishpur", "Bihiya", "Dulanpur"],
    "Koilwar": ["Koilwar", "Kulharia", "Mana"],
    "Piro": ["Piro", "Tarari", "Nasriganj"],
    "Sahar": ["Sahar", "Koilwar", "Agiaon"],
    "Sandesh": ["Sandesh", "Udwantnagar", "Koilwar"],
    "Shahpur": ["Shahpur", "Bihiya", "Karanapul"],
    "Tarari": ["Tarari", "Piro", "Garhani"],
    "Udwantnagar": ["Udwantnagar", "Arrah", "Sandesh"]
  },
  "Buxar": {
    "Buxar": ["Buxar", "Itarhi", "Chakki"],
    "Brahmpur": ["Brahmpur", "Simri", "Raghunathpur"],
    "Chakki": ["Chakki", "Brahmpur", "Simri"],
    "Chausa": ["Chausa", "Buxar", "Keshath"],
    "Dumraon": ["Dumraon", "Nawanagar", "Kesath"],
    "Itarhi": ["Itarhi", "Buxar", "Rajpur"],
    "Keshath": ["Keshath", "Dumraon", "Chausa"],
    "Nawanagar": ["Nawanagar", "Dumraon", "Keshath"],
    "Rajpur": ["Rajpur", "Itarhi", "Buxar"],
    "Simri": ["Simri", "Brahmpur", "Chakki"]
  },
  "Darbhanga": {
    "Alinagar": ["Alinagar", "Benipur", "Baheri"],
    "Aurai": ["Aurai", "Kanti", "Minapur"],
    "Baheri": ["Baheri", "Benipur", "Alinagar"],
    "Bahadurpur": ["Bahadurpur", "Darbhanga", "Keoti"],
    "Benipur": ["Benipur", "Alinagar", "Biraul"],
    "Biraul": ["Biraul", "Ghanshyampur", "Kusheshwar Asthan"],
    "Darbhanga": ["Darbhanga", "Bahadurpur", "Manigachhi"],
    "Ghanshyampur": ["Ghanshyampur", "Biraul", "Kiratpur"],
    "Hanuman Nagar": ["Hanuman Nagar", "Singhwara", "Jale"],
    "Hayaghat": ["Hayaghat", "Bahadurpur", "Darbhanga"],
    "Jale": ["Jale", "Keoti", "Singhwara"],
    "Keoti": ["Keoti", "Jale", "Singhwara"],
    "Kiratpur": ["Kiratpur", "Ghanshyampur", "Biraul"],
    "Kusheshwar Asthan": ["Kusheshwar Asthan", "Kusheshwar Asthan East", "Biraul"],
    "Kusheshwar Asthan East": ["Kusheshwar Asthan East", "Kusheshwar Asthan", "Biraul"],
    "Manigachhi": ["Manigachhi", "Baheri", "Darbhanga"],
    "Singhwara": ["Singhwara", "Jale", "Keoti"],
    "Tardih": ["Tardih", "Benipur", "Biraul"]
  },
  "East Champaran (Purbi Champaran)": {
    "Areraj": ["Areraj", "Harsidhi", "Sangrampur"],
    "Banjaria": ["Banjaria", "Motihari", "Turkauliya"],
    "Barharia": ["Barharia", "Pachpakri", "Madhuban"],
    "Chakia": ["Chakia", "Mehsi", "Kalyanpur"],
    "Dhaka": ["Dhaka", "Pachpakri", "Ghorasahan"],
    "Ghorasahan": ["Ghorasahan", "Dhaka", "Adapur"],
    "Harsidhi": ["Harsidhi", "Areraj", "Paharpur"],
    "Kalyanpur": ["Kalyanpur", "Chakia", "Kesaria"],
    "Kesaria": ["Kesaria", "Kalyanpur", "Areraj"],
    "Lakhaura": ["Lakhaura", "Motihari", "Banjaria"],
    "Madhuban": ["Madhuban", "Pachpakri", "Harpur"],
    "Mehsi": ["Mehsi", "Chakia", "Kalyanpur"],
    "Motihari": ["Motihari", "Banjaria", "Turkauliya"],
    "Paharpur": ["Paharpur", "Areraj", "Harsidhi"],
    "Pakri Dayal": ["Pakri Dayal", "Madhuban", "Phenhara"],
    "Phenhara": ["Phenhara", "Pakri Dayal", "Madhuban"],
    "Raxaul": ["Raxaul", "Adapur", "Ramgarhwa"],
    "Sangrampur": ["Sangrampur", "Areraj", "Harsidhi"],
    "Sugauli": ["Sugauli", "Motihari", "Banjaria"],
    "Turkauliya": ["Turkauliya", "Motihari", "Banjaria"]
  },
  "Gaya": {
    "Atri": ["Atri", "Wazirganj", "Mohanpur"],
    "Wazirganj": ["Wazirganj", "Atri", "Khizarsarai"],
    "Bodh Gaya": ["Bodh Gaya", "Mohanpur", "Manpur"],
    "Dumaria": ["Dumaria", "Imamganj", "Barachatti"],
    "Gurua": ["Gurua", "Banke Bazar", "Amas"],
    "Imamganj": ["Imamganj", "Dumaria", "Sherghati"],
    "Manpur": ["Manpur", "Bodh Gaya", "Gaya Town"],
    "Mohanpur": ["Mohanpur", "Bodh Gaya", "Barachatti"],
    "Sherghati": ["Sherghati", "Dobhi", "Barachatti"],
    "Tekari": ["Tekari", "Belaganj", "Konch"]
  },
  "Gopalganj": {
    "Baikunthpur": ["Baikunthpur", "Dhaama", "Kakrahi"],
    "Barauli": ["Barauli", "Mahuwa", "Manjha"],
    "Bhorey": ["Bhorey", "Katiya", "Pachdeori"],
    "Gopalganj": ["Gopalganj", "Manjha", "Thawe"],
    "Hathua": ["Hathua", "Mirganj", "Uchkagaon"],
    "Katiya": ["Katiya", "Bhorey", "Pachdeori"],
    "Kuchaikote": ["Kuchaikote", "Gopalganj", "Barauli"],
    "Manjha": ["Manjha", "Gopalganj", "Barauli"],
    "Pachdeori": ["Pachdeori", "Bhorey", "Katiya"],
    "Phulwaria": ["Phulwaria", "Hathua", "Uchkagaon"],
    "Sidhwalia": ["Sidhwalia", "Baikunthpur", "Barauli"],
    "Thawe": ["Thawe", "Gopalganj", "Kuchaikote"],
    "Uchkagaon": ["Uchkagaon", "Hathua", "Mirganj"]
  },
  "Jamui": {
    "Barhat": ["Barhat", "Jamui", "Gidhaur"],
    "Chakai": ["Chakai", "Sono", "Batthia"],
    "Gidhaur": ["Gidhaur", "Barhat", "Jamui"],
    "Islampur": ["Islampur", "Sikandra", "Khaira"],
    "Jamui": ["Jamui", "Barhat", "Khaira"],
    "Jhajha": ["Jhajha", "Chakai", "Simultala"],
    "Khaira": ["Khaira", "Jamui", "Sikandra"],
    "Sikandra": ["Sikandra", "Khaira", "Jamui"],
    "Sono": ["Sono", "Chakai", "Jhajha"]
  },
  "Jehanabad": {
    "Ghoshi": ["Ghoshi", "Kako", "Makhdumpur"],
    "Jehanabad": ["Jehanabad", "Kako", "Modanganj"],
    "Kako": ["Kako", "Jehanabad", "Ghoshi"],
    "Makhdumpur": ["Makhdumpur", "Ghoshi", "Ratni Faridpur"],
    "Modanganj": ["Modanganj", "Jehanabad", "Kako"],
    "Ratni Faridpur": ["Ratni Faridpur", "Jehanabad", "Makhdumpur"]
  },
  "Kaimur (Bhabua)": {
    "Adhaura": ["Adhaura", "Bhabua", "Chainpur"],
    "Bhabua": ["Bhabua", "Bhagwanpur", "Kudra"],
    "Bhagwanpur": ["Bhagwanpur", "Bhabua", "Adhaura"],
    "Chainpur": ["Chainpur", "Bhabua", "Chand"],
    "Chand": ["Chand", "Chainpur", "Durgawati"],
    "Durgawati": ["Durgawati", "Kudra", "Mohania"],
    "Kudra": ["Kudra", "Mohania", "Durgawati"],
    "Mohania": ["Mohania", "Durgawati", "Kudra"],
    "Nuaon": ["Nuaon", "Ramgarh", "Bhabua"],
    "Ramgarh": ["Ramgarh", "Nuaon", "Durgawati"],
    "Rampur": ["Rampur", "Bhabua", "Adhaura"]
  },
  "Katihar": {
    "Amdabad": ["Amdabad", "Manihari", "Barari"],
    "Azamnagar": ["Azamnagar", "Barsoi", "Salmari"],
    "Balrampur": ["Balrampur", "Barsoi", "Kadwa"],
    "Barari": ["Barari", "Korha", "Katihar"],
    "Barsoi": ["Barsoi", "Balrampur", "Azamnagar"],
    "Dandkhora": ["Dandkhora", "Katihar", "Pranpur"],
    "Falka": ["Falka", "Korha", "Sameli"],
    "Hasanganj": ["Hasanganj", "Katihar", "Dandkhora"],
    "Kadwa": ["Kadwa", "Balrampur", "Barsoi"],
    "Katihar": ["Katihar", "Dandkhora", "Barari"],
    "Korha": ["Korha", "Falka", "Sameli"],
    "Manihari": ["Manihari", "Amdabad", "Barari"],
    "Mansahi": ["Mansahi", "Katihar", "Manihari"],
    "Pranpur": ["Pranpur", "Katihar", "Dandkhora"],
    "Sameli": ["Sameli", "Korha", "Falka"]
  },
  "Khagaria": {
    "Alauli": ["Alauli", "Khagaria", "Chautham"],
    "Chautham": ["Chautham", "Alauli", "Beldaur"],
    "Gogri": ["Gogri", "Parbatta", "Mansi"],
    "Khagaria": ["Khagaria", "Alauli", "Mansi"],
    "Mansi": ["Mansi", "Khagaria", "Gogri"],
    "Parbatta": ["Parbatta", "Gogri", "Beldaur"],
    "Beldaur": ["Beldaur", "Chautham", "Parbatta"]
  },
  "Kishanganj": {
    "Bahadurganj": ["Bahadurganj", "Kishanganj", "Terhagachh"],
    "Dighalbank": ["Dighalbank", "Thakurganj", "Pothia"],
    "Kishanganj": ["Kishanganj", "Bahadurganj", "Pothia"],
    "Pothia": ["Pothia", "Kishanganj", "Dighalbank"],
    "Terhagachh": ["Terhagachh", "Bahadurganj", "Kochadhaman"],
    "Thakurganj": ["Thakurganj", "Dighalbank", "Pothia"],
    "Kochadhaman": ["Kochadhaman", "Bahadurganj", "Kishanganj"]
  },
  "Lakhisarai": {
    "Barahiya": ["Barahiya", "Lakhisarai", "Suryagarha"],
    "Halsi": ["Halsi", "Ramgarh Chowk", "Lakhisarai"],
    "Lakhisarai": ["Lakhisarai", "Barahiya", "Halsi"],
    "Pipariya": ["Pipariya", "Suryagarha", "Barahiya"],
    "Ramgarh Chowk": ["Ramgarh Chowk", "Halsi", "Lakhisarai"],
    "Suryagarha": ["Suryagarha", "Barahiya", "Pipariya"]
  },
  "Madhepura": {
    "Alamnagar": ["Alamnagar", "Chausa", "Bihariganj"],
    "Bihariganj": ["Bihariganj", "Alamnagar", "Murliganj"],
    "Chausa": ["Chausa", "Alamnagar", "Gualpara"],
    "Gualpara": ["Gualpara", "Madhepura", "Singheshwar"],
    "Ghailarh": ["Ghailarh", "Madhepura", "Singheshwar"],
    "Kishanganj (Madhepura)": ["Kishanganj", "Madhepura", "Kumarkhand"],
    "Kumarkhand": ["Kumarkhand", "Shankarpur", "Madhepura"],
    "Madhepura": ["Madhepura", "Singheshwar", "Ghailarh"],
    "Murliganj": ["Murliganj", "Bihariganj", "Madhepura"],
    "Puraini": ["Puraini", "Alamnagar", "Bihariganj"],
    "Shankarpur": ["Shankarpur", "Kumarkhand", "Madhepura"],
    "Singheshwar": ["Singheshwar", "Madhepura", "Gualpara"]
  },
  "Madhubani": {
    "Andhrathari": ["Andhrathari", "Jhanjharpur", "Madhepur"],
    "Babubarhi": ["Babubarhi", "Khajauli", "Rajnagar"],
    "Basopatti": ["Basopatti", "Benipatti", "Ladania"],
    "Benipatti": ["Benipatti", "Basopatti", "Madhubani"],
    "Bisfi": ["Bisfi", "Rahika", "Madhubani"],
    "Ghoghardiha": ["Ghoghardiha", "Phulparas", "Andhrathari"],
    "Harlakhi": ["Harlakhi", "Basopatti", "Benipatti"],
    "Jainagar": ["Jainagar", "Khajauli", "Ladania"],
    "Jhanjharpur": ["Jhanjharpur", "Andhrathari", "Madhepur"],
    "Kaluahi": ["Kaluahi", "Rajnagar", "Madhubani"],
    "Khajauli": ["Khajauli", "Babubarhi", "Jainagar"],
    "Ladania": ["Ladania", "Jainagar", "Basopatti"],
    "Lakhnaur": ["Lakhnaur", "Jhanjharpur", "Madhepur"],
    "Madhepur": ["Madhepur", "Jhanjharpur", "Andhrathari"],
    "Madhubani": ["Madhubani", "Rahika", "Rajnagar"],
    "Pandaul": ["Pandaul", "Rajnagar", "Madhubani"],
    "Phulparas": ["Phulparas", "Ghoghardiha", "Laukaha"],
    "Rahika": ["Rahika", "Madhubani", "Bisfi"],
    "Rajnagar": ["Rajnagar", "Madhubani", "Babubarhi"],
    "Laukaha": ["Laukaha", "Phulparas", "Laukahi"],
    "Laukahi": ["Laukahi", "Laukaha", "Madhepur"]
  },
  "Munger": {
    "Asarganj": ["Asarganj", "Sultanganj", "Dharhara"],
    "Bariarpur": ["Bariarpur", "Munger", "Kharagpur"],
    "Dharhara": ["Dharhara", "Munger", "Jamalpur"],
    "Jamalpur": ["Jamalpur", "Munger", "Dharhara"],
    "Haveli Kharagpur": ["Kharagpur", "Tarapur", "Bariarpur"],
    "Munger": ["Munger", "Jamalpur", "Bariarpur"],
    "Sangrampur": ["Sangrampur", "Tarapur", "Kharagpur"],
    "Tarapur": ["Tarapur", "Sangrampur", "Kharagpur"]
  },
  "Muzaffarpur": {
    "Aurai": ["Aurai", "Kanti", "Minapur"],
    "Bandra": ["Bandra", "Sakra", "Muzaffarpur"],
    "Baruraj (Motipur)": ["Motipur", "Paru", "Saraiya"],
    "Bochaha": ["Bochaha", "Muzaffarpur", "Sakra"],
    "Gaighat": ["Gaighat", "Bochaha", "Aurai"],
    "Kanti": ["Kanti", "Muzaffarpur", "Minapur"],
    "Kurhani": ["Kurhani", "Sakra", "Muzaffarpur"],
    "Minapur": ["Minapur", "Kanti", "Aurai"],
    "Motipur": ["Motipur", "Paru", "Saraiya"],
    "Mushahari": ["Mushahari", "Muzaffarpur", "Bochaha"],
    "Paru": ["Paru", "Saraiya", "Motipur"],
    "Sakra": ["Sakra", "Kurhani", "Bochaha"],
    "Saraiya": ["Saraiya", "Paru", "Motipur"]
  },
  "Nalanda": {
    "Asthawan": ["Asthawan", "Bihar Sharif", "Bind"],
    "Ben": ["Ben", "Hilsa", "Islampur"],
    "Bihar Sharif": ["Bihar Sharif", "Asthawan", "Noorsarai"],
    "Bind": ["Bind", "Asthawan", "Rahui"],
    "Chandi": ["Chandi", "Islampur", "Hilsa"],
    "Ekangarsarai": ["Ekangarsarai", "Hilsa", "Islampur"],
    "Giriak": ["Giriak", "Rajgir", "Nalanda"],
    "Harnaut": ["Harnaut", "Chandi", "Noorsarai"],
    "Hilsa": ["Hilsa", "Ekangarsarai", "Chandi"],
    "Islampur": ["Islampur", "Ekangarsarai", "Ben"],
    "Karai Parsurai": ["Karai Parsurai", "Hilsa", "Chandi"],
    "Katra": ["Katra", "Silao", "Rajgir"],
    "Nalanda": ["Nalanda", "Rajgir", "Giriak"],
    "Noorsarai": ["Noorsarai", "Bihar Sharif", "Harnaut"],
    "Parwalpur": ["Parwalpur", "Hilsa", "Ekangarsarai"],
    "Rahui": ["Rahui", "Bihar Sharif", "Bind"],
    "Rajgir": ["Rajgir", "Silao", "Giriak"],
    "Sarmera": ["Sarmera", "Asthawan", "Harnaut"],
    "Silao": ["Silao", "Rajgir", "Nalanda"]
  },
  "Nawada": {
    "Akbarpur": ["Akbarpur", "Nawada", "Govindpur"],
    "<bos>223": ["Pakribarwan", "Kashichak", "Warisaliganj"],
    "Gobindpur": ["Gobindpur", "Akbarpur", "Rajauli"],
    "Hisua": ["Hisua", "Nawada", "Nardiganj"],
    "Kashichak": ["Kashichak", "Warisaliganj", "Pakribarwan"],
    "Kowakol": ["Kowakol", "Rajauli", "Akbarpur"],
    "Nardiganj": ["Nardiganj", "Hisua", "Nawada"],
    "Nawada": ["Nawada", "Akbarpur", "Hisua"],
    "Pakribarwan": ["Pakribarwan", "Warisaliganj", "Kashichak"],
    "Rajauli": ["Rajauli", "Kowakol", "Akbarpur"],
    "Roh": ["Roh", "Warisaliganj", "Pakribarwan"],
    "Sirdikalla": ["Sirdikalla", "Akbarpur", "Gobindpur"],
    "Warisaliganj": ["Warisaliganj", "Pakribarwan", "Kashichak"]
  },
  "Patna": {
    "Athmalgola": ["Athmalgola", "Barh", "Belchhi"],
    "Bakhtiyarpur": ["Bakhtiyarpur", "Khusrupur", "Daniyawan"],
    "Barh": ["Barh", "Athmalgola", "Belchhi"],
    "Belchhi": ["Belchhi", "Barh", "Pandarak"],
    "Bihta": ["Bihta", "Maner", "Naubatpur"],
    "Danapur": ["Danapur", "Phulwari Sharif", "Khagaul"],
    "Daniyawan": ["Daniyawan", "Fatuha", "Khusrupur"],
    "Darbhanga": ["Darbhanga"],
    "Dinapur-cum-Khagaul": ["Dinapur", "Khagaul", "Danapur"],
    "Fatuha": ["Fatuha", "Daniyawan", "Khusrupur"],
    "Khusrupur": ["Khusrupur", "Fatuha", "Bakhtiyarpur"],
    "Maner": ["Maner", "Bihta", "Danapur"],
    "Masaurhi": ["Masaurhi", "Dhanrua", "Punpun"],
    "Naubatpur": ["Naubatpur", "Bihta", "Phulwari Sharif"],
    "Paliganj": ["Paliganj", "Dhanaura", "Dulhin Bazar"],
    "Pandarak": ["Pandarak", "Barh", "Mokama"],
    "Phulwari Sharif": ["Phulwari Sharif", "Danapur", "Patna Rural"],
    "Punpun": ["Punpun", "Masaurhi", "Phulwari Sharif"],
    "Sampatchak": ["Sampatchak", "Patna Rural", "Phulwari Sharif"]
  },
  "Purnia": {
    "Amour": ["Amour", "Baisa", "Byasi"],
    "Baisa": ["Baisa", "Amour", "Byasi"],
    "Banmankhi": ["Banmankhi", "Barhara Kothi", "Srinagar"],
    "Barhara Kothi": ["Barhara Kothi", "Banmankhi", "Dhamdaha"],
    "Bhawanipur": ["Bhawanipur", "Rupauli", "Dhamdaha"],
    "Byasi": ["Byasi", "Amour", "Baisa"],
    "Dhamdaha": ["Dhamdaha", "Bhawanipur", "Barhara Kothi"],
    "Jalalgarh": ["Jalalgarh", "Kasba", "Purnia East"],
    "Kasba": ["Kasba", "Jalalgarh", "Purnia East"],
    "Purnia East": ["Purnia East", "Kasba", "Jalalgarh"],
    "Rupauli": ["Rupauli", "Bhawanipur", "Dhamdaha"],
    "Srinagar": ["Srinagar", "Banmankhi", "Purnia East"]
  },
  "Rohtas": {
    "Akbarpur": ["Akbarpur", "Rohtas", "Nauhatta"],
    "Akorhigola": ["Akorhigola", "Dehri", "Sasaram"],
    "Bikramganj": ["Bikramganj", "Karakat", "Nasriganj"],
    "Chenari": ["Chenari", "Sasaram", "Kargahar"],
    "Dhanain": ["Dhanain", "Dinara", "Kargahar"],
    "Dehri": ["Dehri", "Akorhigola", "Tilouthu"],
    "Dinara": ["Dinara", "Dhanain", "Dawath"],
    "Kargahar": ["Kargahar", "Chenari", "Sasaram"],
    "Karakat": ["Karakat", "Bikramganj", "Nasriganj"],
    "Kochas": ["Kochas", "Dinara", "Sasaram"],
    "Nasriganj": ["Nasriganj", "Bikramganj", "Karakat"],
    "Nauhatta": ["Nauhatta", "Rohtas", "Akbarpur"],
    "Nokha": ["Nokha", "Sasaram", "Kargahar"],
    "Rohtas": ["Rohtas", "Nauhatta", "Akbarpur"],
    "Sasaram": ["Sasaram", "Chenari", "Kargahar"],
    "Sanjhauli": ["Sanjhauli", "Bikramganj", "Nokha"],
    "Tilouthu": ["Tilouthu", "Dehri", "Rohtas"]
  },
  "Saharsa": {
    "Banma Itahri": ["Banma Itahri", "Mahishi", "Saur Bazar"],
    "Kahra": ["Kahra", "Saharsa", "Saur Bazar"],
    "Mahishi": ["Mahishi", "Banma Itahri", "Kahra"],
    "Naulakha": ["Naulakha", "Patarghat", "Simri Bakhtiyarpur"],
    "Patarghat": ["Patarghat", "Saur Bazar", "Kahra"],
    "Salkhua": ["Salkhua", "Simri Bakhtiyarpur", "Mahishi"],
    "Saur Bazar": ["Saur Bazar", "Kahra", "Patarghat"],
    "Simri Bakhtiyarpur": ["Simri Bakhtiyarpur", "Salkhua", "Banma Itahri"],
    "Sonbarsa": ["Sonbarsa", "Kahra", "Patarghat"]
  },
  "Samastipur": {
    "Bibhutipur": ["Bibhutipur", "Rosera", "Warisnagar"],
    "Dalsinghsarai": ["Dalsinghsarai", "Ujiarpur", "Vidyapatinagar"],
    "Kalyanpur": ["Kalyanpur", "Pusa", "Samastipur"],
    "Khanpur": ["Khanpur", "Samastipur", "Tajpur"],
    "Mohiuddinagar": ["Mohiuddinagar", "Vidyapatinagar", "Patsa"],
    "Morwa": ["Morwa", "Tajpur", "Pusa"],
    "Patsa": ["Patsa", "Mohiuddinagar", "Dalsinghsarai"],
    "Pusa": ["Pusa", "Kalyanpur", "Morwa"],
    "Rosera": ["Rosera", "Bibhutipur", "Singhia"],
    "Samastipur": ["Samastipur", "Kalyanpur", "Khanpur"],
    "Sarairanjan": ["Sarairanjan", "Ujiarpur", "Samastipur"],
    "Shivaji Nagar": ["Shivaji Nagar", "Rosera", "Singhia"],
    "Singhia": ["Singhia", "Rosera", "Shivaji Nagar"],
    "Tajpur": ["Tajpur", "Morwa", "Khanpur"],
    "Ujiarpur": ["Ujiarpur", "Dalsinghsarai", "Sarairanjan"],
    "Vidyapatinagar": ["Vidyapatinagar", "Mohiuddinagar", "Dalsinghsarai"],
    "Warisnagar": ["Warisnagar", "Rosera", "Samastipur"]
  },
  "Saran (Chapra)": {
    " Amnour": ["Amnour", "Marhaura", "Parsa"],
    "Baniapur": ["Baniapur", "Mashrakh", "Taraiya"],
    "Chapra": ["Chapra", "Garkha", "Manjhi"],
    "Dighwara": ["Dighwara", "Sonpur", "Dariapur"],
    "Ekma": ["Ekma", "Manjhi", "Lawapur"],
    "Garkha": ["Garkha", "Chapra", "Nagra"],
    "Isuapur": ["Isuapur", "Mashrakh", "Baniapur"],
    "Jalalpur": ["Jalalpur", "Chapra", "Maker"],
    "Maker": ["Maker", "Dighwara", "Parsa"],
    "Manjhi": ["Manjhi", "Ekma", "Chapra"],
    "Marhaura": ["Marhaura", "Amnour", "Panapur"],
    "Mashrakh": ["Mashrakh", "Isuapur", "Baniapur"],
    "Nagra": ["Nagra", "Garkha", "Chapra"],
    "Panapur": ["Panapur", "Taraiya", "Marhaura"],
    "Parsa": ["Parsa", "Amnour", "Maker"],
    "Revelganj": ["Revelganj", "Chapra", "Manjhi"],
    "Sonpur": ["Sonpur", "Dighwara", "Dariapur"],
    "Taraiya": ["Taraiya", "Panapur", "Mashrakh"]
  },
  "Sheikhpura": {
    "Ariari": ["Ariari", "Sheikhpura", "Chewara"],
    "Barbigha": ["Barbigha", "Shekhopur Sarai", "Ghat Kusumbha"],
    "Chewara": ["Chewara", "Ariari", "Sheikhpura"],
    "Ghat Kusumbha": ["Ghat Kusumbha", "Sheikhpura", "Barbigha"],
    "Sheikhpura": ["Sheikhpura", "Ariari", "Chewara"],
    "Shekhopur Sarai": ["Shekhopur Sarai", "Barbigha", "Sheikhpura"]
  },
  "Sheohar": {
    "Dumari Katsari": ["Dumari Katsari", "Sheohar", "Tariyani"],
    "Piprahi": ["Piprahi", "Sheohar", "Tariyani"],
    "Purnahiya": ["Purnahiya", "Sheohar", "Dumari Katsari"],
    "Sheohar": ["Sheohar", "Piprahi", "Tariyani"],
    "Tariyani": ["Tariyani", "Sheohar", "Piprahi"]
  },
  "Sitamarhi": {
    "Bairgania": ["Bairgania", "Suppi", "Sonbarsa"],
    "Belsand": ["Belsand", "Runnisaidpur", "Parsauni"],
    "Bathnaha": ["Bathnaha", "Sitamarhi", "Parihar"],
    "Dumra": ["Dumra", "Sitamarhi", "Majorganj"],
    "Majorganj": ["Majorganj", "Sonbarsa", "Dumra"],
    "Nanpur": ["Nanpur", "Runnisaidpur", "Belsand"],
    "Parihar": ["Parihar", "Sursand", "Bathnaha"],
    "Parsauni": ["Parsauni", "Belsand", "Runnisaidpur"],
    "Pupri": ["Pupri", "Nanpur", "Belsand"],
    "Riga": ["Riga", "Sitamarhi", "Dumra"],
    "Runnisaidpur": ["Runnisaidpur", "Belsand", "Parsauni"],
    "Sonbarsa": ["Sonbarsa", "Majorganj", "Bairgania"],
    "Suppi": ["Suppi", "Bairgania", "Sitamarhi"],
    "Sursand": ["Sursand", "Parihar", "Pupri"],
    "Sitamarhi": ["Sitamarhi", "Dumra", "Riga"]
  },
  "Siwan": {
    "Andar": ["Andar", "Raghunathpur", "Darauli"],
    "Barharia": ["Barharia", "Siwan", "Goriakothi"],
    "Basantpur": ["Basantpur", "Maharajganj", "Bhagwanpur Hat"],
    "Bhagwanpur Hat": ["Bhagwanpur Hat", "Maharajganj", "Basantpur"],
    "Darauli": ["Darauli", "Mairwa", "Andar"],
    "Daraunda": ["Daraunda", "Maharajganj", "Siwan"],
    "Goriakothi": ["Goriakothi", "Barharia", "Lakri Nabiganj"],
    "Guthani": ["Guthani", "Mairwa", "Darauli"],
    "Hussainganj": ["Hussainganj", "Siwan", "Ziradei"],
    "Mairwa": ["Mairwa", "Guthani", "Darauli"],
    "Maharajganj": ["Maharajganj", "Daraunda", "Basantpur"],
    "Nautan": ["Nautan", "Siwan", "Hussainganj"],
    "Pachrukhi": ["Pachrukhi", "Siwan", "Barharia"],
    "Raghunathpur": ["Raghunathpur", "Andar", "Hussainganj"],
    "Siwan": ["Siwan", "Pachrukhi", "Hussainganj"],
    "Ziradei": ["Ziradei", "Hussainganj", "Mairwa"],
    "Lakri Nabiganj": ["Lakri Nabiganj", "Goriakothi", "Basantpur"]
  },
  "Supaul": {
    "<bos>147": ["Supaul", "Kishanpur", "Saraigarh"],
    "Basantpur": ["Basantpur", "Pratapganj", "Raghopur"],
    "Chhatapur": ["Chhatapur", "Raghopur", "Tribeniganj"],
    "Kishanpur": ["Kishanpur", "Supaul", "Saraigarh"],
    "Marauna": ["Marauna", "Supaul", "Nirmali"],
    "Nirmali": ["Nirmali", "Marauna", "Saraigarh"],
    "Pratapganj": ["Pratapganj", "Basantpur", "Raghopur"],
    "Raghopur": ["Raghopur", "Chhatapur", "Basantpur"],
    "Saraigarh": ["Saraigarh", "Nirmali", "Kishanpur"],
    "Supaul": ["Supaul", "Kishanpur", "Marauna"],
    "Tribeniganj": ["Tribeniganj", "Chhatapur", "Raghopur"]
  },
  "Vaishali": {
    "Bhagwanpur": ["Bhagwanpur", "Hajipur", "Lalganj"],
    "Bidupur": ["Bidupur", "Hajipur", "Desari"],
    "Chehrakalan": ["Chehrakalan", "Mahnar", "Sahdei Buzurg"],
    "Desari": ["Desari", "Bidupur", "Mahua"],
    "Hajipur": ["Hajipur", "Bhagwanpur", "Bidupur"],
    "Jandaha": ["Jandaha", "Mahua", "Rajapakar"],
    "Lalganj": ["Lalganj", "Vaishali", "Bhagwanpur"],
    "Mahnar": ["Mahnar", "Sahdei Buzurg", "Chehrakalan"],
    "Mahua": ["Mahua", "Jandaha", "Chehrakalan"],
    "Patepur": ["Patepur", "Mahua", "Jandaha"],
    "Raghopur": ["Raghopur", "Bidupur", "Hajipur"],
    "Rajapakar": ["Rajapakar", "Hajipur", "Jandaha"],
    "Sahdei Buzurg": ["Sahdei Buzurg", "Mahnar", "Chehrakalan"],
    "Vaishali": ["Vaishali", "Lalganj", "Bhagwanpur"]
  },
  "West Champaran (Paschim Champaran)": {
    "Bagaha": ["Bagaha-1", "Bagaha-2", "Bairagi", "Paikauli"],
    "Bairia": ["Bairia", "Bettiah", "Sugauli"],
    "Bettiah": ["Bettiah", "Bairia", "Bagaha", "Chanpatia"],
    "Chanpatia": ["Chanpatia", "Bettiah", "Narkatiaganj"],
    "Gaunaha": ["Gaunaha", "Narkatiaganj", "Mainatand"],
    "Lauriya": ["Lauriya", "Narkatiaganj", "Bettiah"],
    "Madhubani (West Champaran)": ["Madhubani", "Bettiah", "Bagaha"],
    "Mainatand": ["Mainatand", "Narkatiaganj", "Gaunaha"],
    "Narkatiaganj": ["Narkatiaganj", "Lauriya", "Gaunaha"],
    " Nautan": ["Nautan", "Bettiah", "Bairia"],
    "Thakrahan": ["Thakrahan", "Bagaha", "Bettiah"]
  }
};
